FROM ruby:3.0-alpine3.16

RUN mkdir /app
WORKDIR /app

ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock

# Install dependencies
RUN apk add --update --no-cache \
    build-base \
    postgresql-dev \
    tzdata

RUN bundle install

COPY . /app

ENV PORT 80
EXPOSE 80
CMD bundle exec rackup --host 0.0.0.0 --port $PORT
