version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: oreoremdm
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    ports:
      - 27017:27017

volumes:
  mongodb-data:
    driver: local
  mongodb-config:
    driver: local
