version: '3'
services:
  web:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://pguser:pgpassword@postgres:5432/pguser
      - MDM_SERVER_BASE_URL
      - PUSH_CERTIFICATE_PASSWORD
      - PUSH_CERTIFICATE_BASE64
      - SERVER_PRIVATE_KEY_BASE64
      - DEVICE_CERTIFICATE_BASE64
    volumes:
      - .:/app
      - bundle-data:/usr/local/bundle
    ports:
      - 3000:3000
    command: bundle exec rackup --host 0.0.0.0 --port 3000

  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pguser

volumes:
  bundle-data:
    driver: local
  pg-data:
    driver: local
