module Command
  class InstallProfile
    def self.template_new
      profile_uuid = SecureRandom.uuid
      new(
        raw_profile: <<~XML
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>PayloadContent</key>
          <array>
            <dict>
              <key>PayloadDescription</key>
              <string>機能制限を構成します</string>
              <key>PayloadDisplayName</key>
              <string>制限</string>
              <key>PayloadIdentifier</key>
              <string>com.apple.applicationaccess.432EB5DB-CA7F-4E9C-B291-7B54BF76475E</string>
              <key>PayloadType</key>
              <string>com.apple.applicationaccess</string>
              <key>PayloadUUID</key>
              <string>432EB5DB-CA7F-4E9C-B291-7B54BF76475E</string>
              <key>PayloadVersion</key>
              <integer>1</integer>
              <key>allowActivityContinuation</key>
              <true/>
              <key>allowAddingGameCenterFriends</key>
              <true/>
              <key>allowAirPlayIncomingRequests</key>
              <true/>
              <key>allowAirPrint</key>
              <true/>
              <key>allowAirPrintCredentialsStorage</key>
              <true/>
              <key>allowAirPrintiBeaconDiscovery</key>
              <true/>
              <key>allowAppCellularDataModification</key>
              <true/>
              <key>allowAppClips</key>
              <true/>
              <key>allowAppInstallation</key>
              <true/>
              <key>allowAppRemoval</key>
              <true/>
              <key>allowApplePersonalizedAdvertising</key>
              <true/>
              <key>allowAssistant</key>
              <true/>
              <key>allowAssistantWhileLocked</key>
              <true/>
              <key>allowAutoCorrection</key>
              <true/>
              <key>allowAutoUnlock</key>
              <true/>
              <key>allowAutomaticAppDownloads</key>
              <true/>
              <key>allowBluetoothModification</key>
              <true/>
              <key>allowBookstore</key>
              <true/>
              <key>allowBookstoreErotica</key>
              <true/>
              <key>allowCamera</key>
              <true/>
              <key>allowCellularPlanModification</key>
              <true/>
              <key>allowChat</key>
              <true/>
              <key>allowCloudBackup</key>
              <true/>
              <key>allowCloudDocumentSync</key>
              <true/>
              <key>allowCloudPhotoLibrary</key>
              <true/>
              <key>allowContinuousPathKeyboard</key>
              <true/>
              <key>allowDefinitionLookup</key>
              <true/>
              <key>allowDeviceNameModification</key>
              <true/>
              <key>allowDeviceSleep</key>
              <true/>
              <key>allowDictation</key>
              <true/>
              <key>allowESIMModification</key>
              <true/>
              <key>allowEnablingRestrictions</key>
              <true/>
              <key>allowEnterpriseAppTrust</key>
              <true/>
              <key>allowEnterpriseBookBackup</key>
              <true/>
              <key>allowEnterpriseBookMetadataSync</key>
              <true/>
              <key>allowEraseContentAndSettings</key>
              <true/>
              <key>allowExplicitContent</key>
              <true/>
              <key>allowFilesNetworkDriveAccess</key>
              <true/>
              <key>allowFilesUSBDriveAccess</key>
              <true/>
              <key>allowFindMyDevice</key>
              <true/>
              <key>allowFindMyFriends</key>
              <true/>
              <key>allowFingerprintForUnlock</key>
              <true/>
              <key>allowFingerprintModification</key>
              <true/>
              <key>allowGameCenter</key>
              <true/>
              <key>allowGlobalBackgroundFetchWhenRoaming</key>
              <true/>
              <key>allowInAppPurchases</key>
              <true/>
              <key>allowKeyboardShortcuts</key>
              <true/>
              <key>allowManagedAppsCloudSync</key>
              <true/>
              <key>allowMultiplayerGaming</key>
              <true/>
              <key>allowMusicService</key>
              <true/>
              <key>allowNews</key>
              <true/>
              <key>allowNotificationsModification</key>
              <true/>
              <key>allowOpenFromManagedToUnmanaged</key>
              <true/>
              <key>allowOpenFromUnmanagedToManaged</key>
              <true/>
              <key>allowPairedWatch</key>
              <true/>
              <key>allowPassbookWhileLocked</key>
              <true/>
              <key>allowPasscodeModification</key>
              <true/>
              <key>allowPasswordAutoFill</key>
              <true/>
              <key>allowPasswordProximityRequests</key>
              <true/>
              <key>allowPasswordSharing</key>
              <true/>
              <key>allowPersonalHotspotModification</key>
              <true/>
              <key>allowPhotoStream</key>
              <true/>
              <key>allowPredictiveKeyboard</key>
              <true/>
              <key>allowProximitySetupToNewDevice</key>
              <true/>
              <key>allowRadioService</key>
              <true/>
              <key>allowRemoteAppPairing</key>
              <true/>
              <key>allowRemoteScreenObservation</key>
              <true/>
              <key>allowSafari</key>
              <true/>
              <key>allowScreenShot</key>
              <true/>
              <key>allowSharedStream</key>
              <true/>
              <key>allowSpellCheck</key>
              <true/>
              <key>allowSpotlightInternetResults</key>
              <true/>
              <key>allowSystemAppRemoval</key>
              <true/>
              <key>allowUIAppInstallation</key>
              <true/>
              <key>allowUIConfigurationProfileInstallation</key>
              <true/>
              <key>allowUSBRestrictedMode</key>
              <true/>
              <key>allowUnpairedExternalBootToRecovery</key>
              <false/>
              <key>allowUntrustedTLSPrompt</key>
              <true/>
              <key>allowVPNCreation</key>
              <true/>
              <key>allowVideoConferencing</key>
              <true/>
              <key>allowVoiceDialing</key>
              <true/>
              <key>allowWallpaperModification</key>
              <true/>
              <key>allowiTunes</key>
              <true/>
              <key>enforcedSoftwareUpdateDelay</key>
              <integer>90</integer>
              <key>enforcedSoftwareUpdateMajorOSDeferredInstallDelay</key>
              <integer>90</integer>
              <key>enforcedSoftwareUpdateMinorOSDeferredInstallDelay</key>
              <integer>90</integer>
              <key>forceAirDropUnmanaged</key>
              <false/>
              <key>forceAirPrintTrustedTLSRequirement</key>
              <false/>
              <key>forceAssistantProfanityFilter</key>
              <false/>
              <key>forceAuthenticationBeforeAutoFill</key>
              <false/>
              <key>forceAutomaticDateAndTime</key>
              <false/>
              <key>forceClassroomAutomaticallyJoinClasses</key>
              <false/>
              <key>forceClassroomRequestPermissionToLeaveClasses</key>
              <false/>
              <key>forceClassroomUnpromptedAppAndDeviceLock</key>
              <false/>
              <key>forceClassroomUnpromptedScreenObservation</key>
              <false/>
              <key>forceDelayedSoftwareUpdates</key>
              <true/>
              <key>forceDelayedAppSoftwareUpdates</key>
              <false/>
              <key>forceDelayedMajorSoftwareUpdates</key>
              <true/>
              <key>forceEncryptedBackup</key>
              <false/>
              <key>forceITunesStorePasswordEntry</key>
              <false/>
              <key>forceLimitAdTracking</key>
              <false/>
              <key>forceWatchWristDetection</key>
              <false/>
              <key>forceWiFiPowerOn</key>
              <false/>
              <key>forceWiFiWhitelisting</key>
              <false/>
              <key>ratingApps</key>
              <integer>1000</integer>
              <key>ratingMovies</key>
              <integer>1000</integer>
              <key>ratingRegion</key>
              <string>jp</string>
              <key>ratingTVShows</key>
              <integer>1000</integer>
              <key>safariAcceptCookies</key>
              <real>2</real>
              <key>safariAllowAutoFill</key>
              <true/>
              <key>safariAllowJavaScript</key>
              <true/>
              <key>safariAllowPopups</key>
              <true/>
              <key>safariForceFraudWarning</key>
              <false/>
            </dict>
          </array>
          <key>PayloadDisplayName</key>
          <string>forceDelaySoftwareUpdate90</string>
          <key>PayloadIdentifier</key>
          <string>oreoremdm.#{profile_uuid}</string>
          <key>PayloadRemovalDisallowed</key>
          <false/>
          <key>PayloadType</key>
          <string>Configuration</string>
          <key>PayloadUUID</key>
          <string>#{profile_uuid}</string>
          <key>PayloadVersion</key>
          <integer>1</integer>
        </dict>
        </plist>
        XML
      )
    end

    def initialize(raw_profile:)
      @command_uuid = SecureRandom.uuid
      @profile = raw_profile
    end

    # https://developer.apple.com/documentation/devicemanagement/install_a_profile
    def request_payload
      {
        CommandUUID: @command_uuid,
        Command: {
          RequestType: 'InstallProfile',
          Payload: StringIO.new(@profile)
        }
      }
    end
  end
end
